title: "Enbo Zhou"
description: "Professional homepage of Enbo Zhou"
baseurl: ""
url: "https://zhouenbo.github.io"

markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag

author:
  name: "Enbo Zhou"
  email: "ebzhou@geog.ucsb.edu"

collections:
  posts:
    output: true

