title: Enbo Zhou
position: Ph.D.
affiliation: UC Santa Barbara
email: enbozhou@ucsb.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=Znr0WhAAAAAJ&hl=en
github_link: https://github.com/
linkedin: https://www.linkedin.com/in/enbo-zhou-179b56a1/
cv_link: 
avatar: ./assets/img/EnboZhou.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Strata Academic is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
